%% Code for flowchart below
flowchart LR
    A((Step1))
    B((Step2))
    C((Step3))
    D((Step4))
    E((Step5))
    F((Step6))
    A --next--> B
    B --next--> C
    B --next--> D
    D --next--> E
    E --next--> F
    C --next--> F
