%% Code for flowchart below
graph LR
    ssot[SSOT Nodes]

    A[Modify Nodes]
    B[Modify Edges]
    
    A --modify--> ssot
    B --update--> ssot
    ssot --signals--> edges

    backend[Backend]

    ssot --"run graphs.json"--> backend

    outputs((LLM\nOutputs))
    backend --> outputs